/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'imagePath' : IDL.Text,
  'name' : IDL.Text,
  'specs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'shortDescription' : IDL.Text,
  'category' : IDL.Text,
  'fullDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'imagePath' : IDL.Text,
    'name' : IDL.Text,
    'specs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'shortDescription' : IDL.Text,
    'category' : IDL.Text,
    'fullDescription' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };